apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-marketplace
  namespace: watchlist
spec:
  selector:
    matchLabels:
      app: movies-marketplace
  template:
    metadata: 
      labels: 
        app: movies-marketplace
    spec:
      containers:
      - name: movies-marketplace
        image: skyglass/movies-marketplace:develop
        imagePullPolicy: Always
        ports:
        - containerPort: 80